# Site settings
title: soundwanders
email: soundwanders@jekyll.site
url: https://soundwanders.github.io/portfolio
description: "A mock portfolio site built with Jerome Michaud's Bootstrap + Jekyll template."
keywords: "html, css, javascript, jekyll, bootstrap, portfolio, website"
trade: "Front-End Developer"
meta_author: soundwanders

# # Google webmaster tools
# google_verify:

# # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# # If you use disqus you need disqus shortname
# # https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: null

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 389cff
  primary-rgb: "56, 156, 255" #rgb(22%,61.2%,100%)
  secondary: 2c4150
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: soundwanders
  location: Location
  social: Around the Web
  credits: Credits

# Social networks
social:
  - title: stack-overflow
    url: https://stackoverflow.com
  - title: linkedin
    url: https://linkedin.com
  - title: github
    url: https://github.com

# Postal address (add as many lines as necessary)
address:
  - line: Kilgore Trout

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
