# Site settings
title: soundwanders
email: soundwanders@gmail.com
url: https://soundwanders.github.io/portfolio
description: "Jared Coletta developer portfolio."
keywords: "html, css, javascript, jekyll, bootstrap, portfolio, website"
skills: "Front-End Web Developer"
meta_author: soundwanders

# # Google webmaster tools
# google_verify:

# # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# # If you use disqus you need disqus shortname
# # https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: null

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 389cff
  primary-rgb: rgb(255, 181, 108)
  secondary: 2c4150
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: soundwanders
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: https://stackoverflow.com/users/14271738/soundwanders
  - title: linkedin
    url: https://www.linkedin.com/in/jared-coletta-205882116
  - title: github
    url: https://github.com/soundwanders

# Postal address (add as many lines as necessary)
address:
  - line: New Hampshire, United States

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
